/// Flutter icons GiftShopAppIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GiftShopAppIcon
///      fonts:
///       - asset: fonts/GiftShopAppIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class GiftShopAppIcon {
  GiftShopAppIcon._();

  static const _kFontFam = 'GiftShopAppIcon';

  static const IconData user = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData valentines_day =
      IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData woman = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData birthday_cake = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData box = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData children = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData favourite = IconData(0xe813, fontFamily: _kFontFam);
  static const IconData filter = IconData(0xe814, fontFamily: _kFontFam);
  static const IconData graduation_hat =
      IconData(0xe815, fontFamily: _kFontFam);
  static const IconData home = IconData(0xe816, fontFamily: _kFontFam);
  static const IconData mother = IconData(0xe817, fontFamily: _kFontFam);
  static const IconData new_house = IconData(0xe818, fontFamily: _kFontFam);
  static const IconData teaching = IconData(0xe819, fontFamily: _kFontFam);
}
